/*Auto generated code*/

#include "InterruptVector.h"
#include "ModuleController.h"

ISR(USARTC0_RXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTC0_IDX)]->interruptVector_.Receive->onUsartReceive();}
ISR(USARTC0_DRE_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTC0_IDX)]->interruptVector_.DataRegisterEmpty->onUsartDataRegisterEmpty();}
ISR(USARTC0_TXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTC0_IDX)]->interruptVector_.Transmit->onUsartTransmit();}
ISR(USARTC1_RXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTC1_IDX)]->interruptVector_.Receive->onUsartReceive();}
ISR(USARTC1_DRE_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTC1_IDX)]->interruptVector_.DataRegisterEmpty->onUsartDataRegisterEmpty();}
ISR(USARTC1_TXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTC1_IDX)]->interruptVector_.Transmit->onUsartTransmit();}
ISR(USARTD0_RXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTD0_IDX)]->interruptVector_.Receive->onUsartReceive();}
ISR(USARTD0_DRE_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTD0_IDX)]->interruptVector_.DataRegisterEmpty->onUsartDataRegisterEmpty();}
ISR(USARTD0_TXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTD0_IDX)]->interruptVector_.Transmit->onUsartTransmit();}
ISR(USARTD1_RXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTD1_IDX)]->interruptVector_.Receive->onUsartReceive();}
ISR(USARTD1_DRE_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTD1_IDX)]->interruptVector_.DataRegisterEmpty->onUsartDataRegisterEmpty();}
ISR(USARTD1_TXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTD1_IDX)]->interruptVector_.Transmit->onUsartTransmit();}
ISR(USARTE0_RXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTE0_IDX)]->interruptVector_.Receive->onUsartReceive();}
ISR(USARTE0_DRE_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTE0_IDX)]->interruptVector_.DataRegisterEmpty->onUsartDataRegisterEmpty();}
ISR(USARTE0_TXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTE0_IDX)]->interruptVector_.Transmit->onUsartTransmit();}
ISR(USARTE1_RXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTE1_IDX)]->interruptVector_.Receive->onUsartReceive();}
ISR(USARTE1_DRE_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTE1_IDX)]->interruptVector_.DataRegisterEmpty->onUsartDataRegisterEmpty();}
ISR(USARTE1_TXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTE1_IDX)]->interruptVector_.Transmit->onUsartTransmit();}
ISR(USARTF0_RXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTF0_IDX)]->interruptVector_.Receive->onUsartReceive();}
ISR(USARTF0_DRE_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTF0_IDX)]->interruptVector_.DataRegisterEmpty->onUsartDataRegisterEmpty();}
ISR(USARTF0_TXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTF0_IDX)]->interruptVector_.Transmit->onUsartTransmit();}
ISR(USARTF1_RXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTF1_IDX)]->interruptVector_.Receive->onUsartReceive();}
ISR(USARTF1_DRE_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTF1_IDX)]->interruptVector_.DataRegisterEmpty->onUsartDataRegisterEmpty();}
ISR(USARTF1_TXC_vect) {UsartController::instances_[static_cast<uint8_t>(UsartController::Index::USARTF1_IDX)]->interruptVector_.Transmit->onUsartTransmit();}
ISR(TCC0_OVF_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC0_IDX)]->interruptVector_.Overflow->onCounterOverflow();}
ISR(TCC0_ERR_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC0_IDX)]->interruptVector_.Error->onCounterError();}
ISR(TCC0_CCA_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC0_IDX)]->interruptVector_.Channel[0]->onCounterChannel();}
ISR(TCC0_CCB_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC0_IDX)]->interruptVector_.Channel[1]->onCounterChannel();}
ISR(TCC0_CCC_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC0_IDX)]->interruptVector_.Channel[2]->onCounterChannel();}
ISR(TCC0_CCD_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC0_IDX)]->interruptVector_.Channel[3]->onCounterChannel();}
ISR(TCD0_OVF_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD0_IDX)]->interruptVector_.Overflow->onCounterOverflow();}
ISR(TCD0_ERR_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD0_IDX)]->interruptVector_.Error->onCounterError();}
ISR(TCD0_CCA_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD0_IDX)]->interruptVector_.Channel[0]->onCounterChannel();}
ISR(TCD0_CCB_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD0_IDX)]->interruptVector_.Channel[1]->onCounterChannel();}
ISR(TCD0_CCC_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD0_IDX)]->interruptVector_.Channel[2]->onCounterChannel();}
ISR(TCD0_CCD_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD0_IDX)]->interruptVector_.Channel[3]->onCounterChannel();}
ISR(TCE0_OVF_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE0_IDX)]->interruptVector_.Overflow->onCounterOverflow();}
ISR(TCE0_ERR_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE0_IDX)]->interruptVector_.Error->onCounterError();}
ISR(TCE0_CCA_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE0_IDX)]->interruptVector_.Channel[0]->onCounterChannel();}
ISR(TCE0_CCB_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE0_IDX)]->interruptVector_.Channel[1]->onCounterChannel();}
ISR(TCE0_CCC_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE0_IDX)]->interruptVector_.Channel[2]->onCounterChannel();}
ISR(TCE0_CCD_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE0_IDX)]->interruptVector_.Channel[3]->onCounterChannel();}
ISR(TCF0_OVF_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF0_IDX)]->interruptVector_.Overflow->onCounterOverflow();}
ISR(TCF0_ERR_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF0_IDX)]->interruptVector_.Error->onCounterError();}
ISR(TCF0_CCA_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF0_IDX)]->interruptVector_.Channel[0]->onCounterChannel();}
ISR(TCF0_CCB_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF0_IDX)]->interruptVector_.Channel[1]->onCounterChannel();}
ISR(TCF0_CCC_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF0_IDX)]->interruptVector_.Channel[2]->onCounterChannel();}
ISR(TCF0_CCD_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF0_IDX)]->interruptVector_.Channel[3]->onCounterChannel();}
ISR(TCC1_OVF_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC1_IDX)]->interruptVector_.Overflow->onCounterOverflow();}
ISR(TCC1_ERR_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC1_IDX)]->interruptVector_.Error->onCounterError();}
ISR(TCC1_CCA_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC1_IDX)]->interruptVector_.Channel[0]->onCounterChannel();}
ISR(TCC1_CCB_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC1_IDX)]->interruptVector_.Channel[1]->onCounterChannel();}
ISR(TCC1_CCC_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC1_IDX)]->interruptVector_.Channel[2]->onCounterChannel();}
ISR(TCC1_CCD_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCC1_IDX)]->interruptVector_.Channel[3]->onCounterChannel();}
ISR(TCD1_OVF_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD1_IDX)]->interruptVector_.Overflow->onCounterOverflow();}
ISR(TCD1_ERR_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD1_IDX)]->interruptVector_.Error->onCounterError();}
ISR(TCD1_CCA_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD1_IDX)]->interruptVector_.Channel[0]->onCounterChannel();}
ISR(TCD1_CCB_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD1_IDX)]->interruptVector_.Channel[1]->onCounterChannel();}
ISR(TCD1_CCC_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD1_IDX)]->interruptVector_.Channel[2]->onCounterChannel();}
ISR(TCD1_CCD_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCD1_IDX)]->interruptVector_.Channel[3]->onCounterChannel();}
ISR(TCE1_OVF_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE1_IDX)]->interruptVector_.Overflow->onCounterOverflow();}
ISR(TCE1_ERR_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE1_IDX)]->interruptVector_.Error->onCounterError();}
ISR(TCE1_CCA_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE1_IDX)]->interruptVector_.Channel[0]->onCounterChannel();}
ISR(TCE1_CCB_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE1_IDX)]->interruptVector_.Channel[1]->onCounterChannel();}
ISR(TCE1_CCC_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE1_IDX)]->interruptVector_.Channel[2]->onCounterChannel();}
ISR(TCE1_CCD_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCE1_IDX)]->interruptVector_.Channel[3]->onCounterChannel();}
ISR(TCF1_OVF_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF1_IDX)]->interruptVector_.Overflow->onCounterOverflow();}
ISR(TCF1_ERR_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF1_IDX)]->interruptVector_.Error->onCounterError();}
ISR(TCF1_CCA_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF1_IDX)]->interruptVector_.Channel[0]->onCounterChannel();}
ISR(TCF1_CCB_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF1_IDX)]->interruptVector_.Channel[1]->onCounterChannel();}
ISR(TCF1_CCC_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF1_IDX)]->interruptVector_.Channel[2]->onCounterChannel();}
ISR(TCF1_CCD_vect) {CounterController::instances_[static_cast<uint8_t>(CounterController::Index::TCF1_IDX)]->interruptVector_.Channel[3]->onCounterChannel();}
ISR(TWIC_TWIS_vect) {TwiController::instances_[static_cast<uint8_t>(TwiController::Index::TWIC_IDX)]->interruptVector_.SlaveEvent->onTwiSlaveEvent();}
ISR(TWIC_TWIM_vect) {TwiController::instances_[static_cast<uint8_t>(TwiController::Index::TWIC_IDX)]->interruptVector_.MasterEvent->onTwiMasterEvent();}
ISR(TWID_TWIS_vect) {TwiController::instances_[static_cast<uint8_t>(TwiController::Index::TWID_IDX)]->interruptVector_.SlaveEvent->onTwiSlaveEvent();}
ISR(TWID_TWIM_vect) {TwiController::instances_[static_cast<uint8_t>(TwiController::Index::TWID_IDX)]->interruptVector_.MasterEvent->onTwiMasterEvent();}
ISR(TWIE_TWIS_vect) {TwiController::instances_[static_cast<uint8_t>(TwiController::Index::TWIE_IDX)]->interruptVector_.SlaveEvent->onTwiSlaveEvent();}
ISR(TWIE_TWIM_vect) {TwiController::instances_[static_cast<uint8_t>(TwiController::Index::TWIE_IDX)]->interruptVector_.MasterEvent->onTwiMasterEvent();}
ISR(TWIF_TWIS_vect) {TwiController::instances_[static_cast<uint8_t>(TwiController::Index::TWIF_IDX)]->interruptVector_.SlaveEvent->onTwiSlaveEvent();}
ISR(TWIF_TWIM_vect) {TwiController::instances_[static_cast<uint8_t>(TwiController::Index::TWIF_IDX)]->interruptVector_.MasterEvent->onTwiMasterEvent();}
